// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  // Credenciais hardcoded para garantir o funcionamento imediato no Vercel
  const SUPABASE_URL = "https://fnocpwvhstwfpcsvscdv.supabase.co";
  const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZub2Nwd3Zoc3R3ZnBjc3ZzY2R2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg1NTA1MDQsImV4cCI6MjA5NDEyNjUwNH0.vP4PrBLKmYTIce7vw3FbeJvjQfrXX3BIwkVhbirjs4E";

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

